app/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import IndexView, LoginRequiredView


urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('login_required', LoginRequiredView.as_view(), name="login_required"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('my_app/', include('my_app.urls'))
]

my_app/urls.py
from django.urls import path, include
from rest_framework import routers


# from .serializers.item import ItemSerializer
from .view_sets.item import ItemViewSet
from .views.dashboard import DashboardView
from .views.item import ItemView
from .views.api.user_favorite_item import UserFavoriteItemAPIView

app_name = "my_app"
urlpatterns = [
    path('dashboard', DashboardView.as_view(), name="dashboard"),
    path('item', ItemView.as_view(), name="item"),
    path(r'api/item_favorite', UserFavoriteItemAPIView.as_view())
]

users/urls.py
from django.urls import path, include
from .views import logout_auth0

app_name = "users"
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('social_django.urls')),
    path('logout', logout_auth0, name="logout"),
]

my_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
import ulid

class ItemModel(models.Model):
    id = models.CharField(max_length=32, default=ulid.new, primary_key=True, editable=False)
    name = models.CharField(max_length=256)
    price = models.IntegerField()
    
    class Meta:
        db_table = "item"


class UserFavoriteItemModel(models.Model):
    id = models.CharField(max_length=32, default=ulid.new, primary_key=True, editable=False)
    item = models.ForeignKey(ItemModel, db_column="item_id", on_delete=models.CASCADE, null=False, blank=False)
    user = models.ForeignKey(get_user_model(), db_column="user_id", on_delete=models.CASCADE, null=False, blank=False)
    
    class Meta:
        db_table = "user_favorite_item"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db.models.fields import BLANK_CHOICE_DASH
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail
import ulid


class CustomUserManager(UserManager):
    '''
    Userを作成するための処理
    Userの項目が変更になっているので、こちらも変更の必要がある
    '''    
    
    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    
    def create_user(self, email=None, password=None, **extra_fields):
        '''
        一般ユーザーを作成する処理
        '''
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)
    
    
    def create_superuser(self, email=None, password=None, **extra_fields):
        '''
        管理者ユーザーを作成する処理
        '''
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)



class User(AbstractBaseUser, PermissionsMixin):
    '''
    カスタムUser
    AbstractBaseUser: 標準のUserモデル
    ※AbstractUserというモデルもあり、これを継承することもできるが、柔軟性が低くなるため非推奨(項目を追加するのみ等の微小なカスタマイズの場合はOK)
    PermissionsMixin: 権限関連のモデル
    '''    
    
    '''
    必須項目
    '''
    id = models.CharField(max_length=32, default=ulid.new, primary_key=True, editable=False) # idは推測されずらく重複しないように、ulidを使用する
    email = models.EmailField(_('メールアドレス'), blank=False, unique=True, db_index=True) 
    full_name = models.CharField(_('氏名'), max_length=150, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    
    # UserManagerを指定
    objects = CustomUserManager()

    '''
    カスタマイズ項目 必要な項目は以下のように追加する
    '''
    nickname = models.CharField(_('ニックネーム'), max_length=32, blank=True)
    gender = models.IntegerField(_('性別'), blank=True, default=0)
    
    '''
    フィールド設定
    '''
    # emailの項目名を指定
    EMAIL_FIELD = 'email'
    # ログイン時にIDになる項目名を指定
    USERNAME_FIELD = 'email'
    # 必須入力とする項目名(USERNAME_FIELDに指定した項目は必ず指定する前提のため指定しない)
    REQUIRED_FIELDS = ['nickname', ]
    
    
    class Meta:
        '''
        テーブル定義(基本は変更しない)
        '''
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = "auth_user"

    
    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)


    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


    def get_full_name(self):
        return self.full_name


    def get_short_name(self):
        return self.full_name
    


    

app/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "index.html"
    
    
class LoginRequiredView(TemplateView):
    template_name = "login_required.html"

my_app/views/dashboard.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.views.generic import TemplateView

app_name = "my_app"

class DashboardView(TemplateView):
    template_name = f"{app_name}/dashboard.html"

my_app/views/item.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.views.generic import TemplateView
from ..models import ItemModel, UserFavoriteItemModel

app_name = "my_app"

class ItemView(TemplateView):
    template_name = f"{app_name}/item.html"
    
    def get(self, request):
        items = ItemModel.objects.all()
        favorite_items = UserFavoriteItemModel.objects.filter(user=request.user).all()
        for item in items:
            item.is_favorited = False
            for favorite_item in favorite_items:
                if item.id == favorite_item.item_id:
                    item.is_favorited = True
                    break
        return self.render_to_response({"items": items})

users/views.py
from django.contrib.auth import logout as log_out
from django.conf import settings
from django.http import HttpResponseRedirect
from urllib.parse import urlencode

from app.settings import LOGOUT_URL


def logout_auth0(request):
    log_out(request)
    return_to = urlencode({'returnTo': request.build_absolute_uri(LOGOUT_URL)})
    logout_url = 'https://%s/v2/logout?client_id=%s&%s' % \
                 (settings.SOCIAL_AUTH_AUTH0_DOMAIN, settings.SOCIAL_AUTH_AUTH0_KEY, return_to)
    return HttpResponseRedirect(logout_url)

templates/index.html
<html>
<head>
</head>
<body>
    <p>トップページ</p>
    <a href="{% url 'users:login' %}auth0">ログイン</a>
</body>
</html>

templates/login_required.html
<html>
<head>
</head>
<body>
    <p>ログインが必要なページです。ログインしてください。</p>
    <a href="{% url 'users:login' %}auth0">ログイン</a>
</body>
</html>

templates/my_app/dashboard.html
<html>
<head>
</head>
<body>
    <p>[ログイン中です] email: {{ user.email }}</p>
    <a href="{% url 'users:logout' %}">ログアウト</a>
</body>
</html>

templates/my_app/item.html
<html>
<head>
</head>
<body>

<p>[ログイン中です] email: {{ user.email }}</p>
<a href="{% url 'users:logout' %}">ログアウト</a>

<label>
    {% for item in items %}
        <div>
            {{ item.name }}
            <input 
                type="button" 
                name="favoriteItem" 
                {% if item.is_favorited %} value="いいね済" {% else %} value="いいね！" {% endif %} 
                data-item_id="{{ item.id }}">
        </div>
    {% endfor %}
</label>

<script>
    const CSRF_TOKEN = '{{ csrf_token }}'
    for(let elm of document.getElementsByName("favoriteItem")){
        elm.addEventListener("click", (e)=>{
            favoriteItem(e.target.dataset.item_id)
            e.target.value = "いいね済"
        })
    }
    async function favoriteItem(itemId){
        const postData = JSON.stringify({
            item_id: itemId
        })
        res = await executeAPI("api/item_favorite", postData, "POST")
        if(res){

        }
    }

    async function executeAPI(url, body, method) {
        try {
            const headers = {
                'content-type': 'application/json',
                'X-CSRFToken': CSRF_TOKEN
            }
            const res = await fetch(
                url, 
                {
                    method: method,
                    headers: headers,
                    body: body
                }
            )
            if (res.status >= 200 && res.status < 300) {
                return await res;
            }
            else {
                alert("APIエラー")
                console.log(res)
                return null;
            }
        } catch (e) {
            console.log(e);
            return null;
        }
    }
</script>
</body>
</html>